### ISSUE TITLE
Strings out of `secrets` are leaking in captured state.

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#116]
With the introduction of state serialization in 27986215c360fc2d72ba04f4d0b1e34936694b8a, an interesting side-effect is revealed: the serialized state may contain -- and leak! -- the secrets. So, if I want to capture this state for later runs, I 

My intuition is that we need to reimplement the `secrets` node to output a `Capability` rather than a string. All consumers of `secrets` node will have to learn how to handle it, but such is the price of progress.

Open to other ideas, obviously!

**Comment by seefeldb** [comment]
Ah, a couple thoughts here, touching on security and serialization in general:

- Yes, the capability could work. But then you have to introduce the ability to serialize capabilities. We'll need that anyway, but this and many others (e.g. a db handle) boil down to rerunning the first node. So:
- For round tripping serialization it might be more efficient to only capture the state that can't easily be recreated by running those parts of the graph again. We might want that in other cases as well, e.g. when a user query expands into a (deterministic) set of much larger results (for example querying a database of locations or documents), then it's often better to rerun that query than to send the huge results over the wire each time. The principle here might be to flip the mental model around and capture the undeterminstic state, i.e. user input and undeterminstic things like generateText.

But there are a few other fundamentals to consider which might point to easier short-term solutions:
- If the (untrusted) user can modify the state before returning it, that might cause all kinds of problems. So you'll have to sign it anyway. In the cloud function scenario that could be an HMAC or so. That is, we already have a secret key:
- you could encrypt the whole state, or parts of the state.
- integrity analysis produces labels for each node and edge that let you know which need to be encrypted, so no need to special case `secrets`.
  - this is also useful when rendering state for debugging purposes: we can redact those parts before rendering them on the screen
  - not sure it's worth it, but in principle you could make that a generic capability itself: wrap a value in an encryption key, then write into the serialized graph the instructions on how to decrypt it.
- speaking of integrity analysis: we might have to serialize that as well (and then the signature is even more important). Maybe we can reconstruct it from reading the graph again, but with dynamic includes that won't work, since the history matters.
- unencrypted state also leaks part of the graph, maybe that's undesired!
- instead we could also store the state server side and just ship a key around. (Conceptually we have storage that is trusted with that level of confidentiality that can produce a handle to the data that itself is declassified enough to be shipped)

I think you'll need at least some of the second part anyway for security. Maybe that's then enough, or otherwise you might need some of the first part as well.

One thing I realized here is that capturing state for local resume, debugging, etc, is quite different from over-the-wire state that might be seen by untrusted parties and/or is long lived.

**Comment by dglazkov** [comment]
> instead we could also store the state server side and just ship a key around.

This feels like a very easy thing to try next. I may just do that.

**Comment by dglazkov** [comment]
Done in a1953f46cd552b987adbf3060b93c398bf74c7fd

**Comment by dglazkov** [comment]
It's a ticket-based system: the actual state is stored in Firestore, and only a ticket to this state is being passed around between the cloud function and the client.

**Comment by dglazkov** [comment]
Declaring partial victory!
