### ISSUE TITLE
Teach `include` and `slot` to resolve URLs correctly

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#118]
It's a total mish-mash currently, and ideally, all of this works in the same fashion that ES Modules and CSS stylesheets work -- URLs are resolved relative to the URL of the graph where they are mentioned.

This would enable running graphs that include other graphs as Cloud Functions #105.

**Comment by seefeldb** [comment]
+1 on relative URLs.

But I don't grok the second part, or do you mean it metaphorically, i.e. it's not actually calling another cloud function but including the graph that would otherwise power a cloud function?

I'd prefer directly including for several reasons:
 - it's faster and cheaper (it appears that production cloud function users tend to combine smaller ones as well for the same reasons)
 - integrity is much harder / more limited this way: we're already getting into all the trusting remote server / understanding remote graphs work, which I was hoping I don't need to worry about for a while. I can give you a few examples of what becomes harder if you like.

That's orthogonal to each graph _also_ being a cloud function. It's just that ideally we stay "inside" breadboard across many graphs.

**Comment by dglazkov** [comment]
Yep, it will just include them directly, not as another cloud function. The same cloud function runs the whole constellation of graphs.

Concrete example: CF can't run `call-react-with-slot.json`, because the URL resolution is relative to the working dir.
